#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMIT_MSG_FILE="$1"

# 첫 줄 가져오기
FIRST_LINE=$(head -n 1 "$COMMIT_MSG_FILE")

# 1. Conventional Commit 형식 검사
echo "$FIRST_LINE" | grep -qE '^(asset|design|build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\(.+\))?!?: .+'

if [ $? -ne 0 ]; then
    echo "커밋 메시지는 'type: 설명' 형식이어야 합니다."
    exit 1
fi

# 2. 첫 줄을 제외한 description의 비어있지 않은 줄 개수 확인
DESCRIPTION_LINES=$(tail -n +2 "$COMMIT_MSG_FILE" | grep -v '^[[:space:]]*$' | wc -l)

if [ "$DESCRIPTION_LINES" -lt 1 ]; then
    echo "커밋 메시지 description은 최소 1줄 이상 작성해야 합니다."
    exit 1
fi

exit 0